version: '2'
services:

  front-react:
    build:
      context: ./client

    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "5000:5000"
      - "9000:9000"

  server-dev:
    build:
      context: ./server

    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db-dev
      - mongodb
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules

  db-dev:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-dev
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=chat-dev
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

volumes:
  server-dev:
